from __future__ import annotations


HARNESS_SAMPLE_GAP_PATTERNS: tuple[str, ...] = (
    "docs/ai/standards/harness-sample-gap-evidence*",
    "docs/ai/standards/harness-future-work-contracts.jsonl",
    "docs/ai/agentic-harness-gap-roadmap.md",
    ".github/workflows/governance-and-smoke.yml",
    "scripts/change_triggered_harness_sample_rules.py",
    "scripts/collect_harness_sample_gaps.py",
    "scripts/check_harness_collection_config.py",
    "scripts/check_harness_sample_gap_evidence.py",
    "scripts/evidence_ref_utils.py",
    "scripts/plan_harness_sample_collection.py",
    "scripts/harness_sample_capture_gates.py",
    "scripts/harness_sample_collection_config.py",
    "scripts/harness_sample_collection_items.py",
    "scripts/harness_sample_collection_render.py",
    "scripts/harness_collection_command_coverage.py",
    "scripts/harness_collection_command_templates.py",
    "scripts/harness_collection_lane_commands.py",
    "scripts/harness_sample_followup_coverage_config.py",
    "scripts/harness_pending_queue_state.py",
    "scripts/harness_sample_boundary.py",
    "scripts/harness_sample_priorities.py",
    "scripts/harness_sample_slots.py",
    "scripts/harness_sample_pending_summaries.py",
    "scripts/harness_pending_readiness_metrics.py",
    "scripts/harness_pending_sample_report.py",
    "scripts/harness_pending_review_cards.py",
    "scripts/harness_pending_capture_focus.py",
    "scripts/harness_pending_capture_focus_filters.py",
    "scripts/harness_pending_capture_focus_render.py",
    "scripts/harness_pending_capture_focus_slots.py",
    "scripts/harness_sample_templates.py",
    "scripts/harness_sample_template_records.py",
    "scripts/harness_sample_outcome_templates.py",
    "scripts/harness_sample_review_commands.py",
    "scripts/harness_sample_intake_render.py",
    "scripts/check_harness_sample_templates.py",
    "scripts/build_harness_sample_intake_bundle.py",
    "scripts/check_harness_placeholder_replacement.py",
    "scripts/check_harness_sample_append.py",
    "scripts/harness_sample_review_context.py",
    "scripts/check_harness_sample_outcome.py",
    "scripts/harness_sample_outcome_context.py",
    "scripts/harness_sample_outcome_validation.py",
    "scripts/check_harness_burn_in_readiness.py",
    "scripts/harness_burn_in_readiness_cli.py",
    "scripts/harness_burn_in_readiness_deltas.py",
    "scripts/harness_burn_in_readiness_filters.py",
    "scripts/harness_burn_in_readiness_render.py",
    "scripts/harness_burn_in_readiness_routing.py",
    "scripts/harness_burn_in_readiness_types.py",
    "scripts/check_harness_pending_samples.py",
    "scripts/check_harness_future_work_contracts.py",
    "scripts/check_harness_future_work_contract_candidate.py",
    "scripts/harness_future_work_contract_context.py",
    "scripts/check_harness_upgrade_decision_candidate.py",
    "scripts/harness_upgrade_decision_context.py",
    "scripts/check_harness_sample_followup_coverage.py",
    "tests/test_harness_sample_gaps.py",
    "tests/test_harness_collection_config.py",
    "tests/test_harness_sample_gap_evidence.py",
    "tests/test_plan_harness_sample_collection.py",
    "tests/test_harness_sample_templates.py",
    "tests/test_harness_sample_intake_bundle.py",
    "tests/test_harness_placeholder_replacement.py",
    "tests/test_harness_sample_append.py",
    "tests/test_harness_sample_outcome.py",
    "tests/test_harness_burn_in_readiness.py",
    "tests/test_harness_pending_samples.py",
    "tests/test_harness_future_work_contracts.py",
    "tests/test_harness_future_work_contract_candidate.py",
    "tests/test_harness_upgrade_decision_candidate.py",
    "tests/test_harness_sample_followup_coverage.py",
    "tests/test_governance_workflow_sample_outputs.py",
)

HARNESS_SAMPLE_GAP_COMMANDS: tuple[str, ...] = (
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_gap_evidence.py",
    "python3 tests/test_harness_sample_gap_evidence.py",
    ".codex/hooks/run_with_repo_python.sh scripts/collect_harness_sample_gaps.py",
    "python3 tests/test_harness_sample_gaps.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_collection_config.py",
    "python3 tests/test_harness_collection_config.py",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --gap-id GAP-DOES-NOT-EXIST --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --ledger-action append-new-pending-slot --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --ledger-action fill-existing-placeholder --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --ledger-action review-upgrade-decision --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-approved-remote-interop --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-approved-bounded-incident --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate replace-placeholder-after-real-event --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-security-workflow-event --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-bounded-real-incident --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-workflow-task-event --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-real-event --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-cross-task-resume --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-distinct-task-class-report --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --capture-gate requires-user-confirmed-high-impact-action --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --readiness needs-first-real-sample --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --readiness needs-more-real-samples --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --readiness ready-for-upgrade-discussion --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --include-accepted --readiness local-sample-only --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area agentic-red-team --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area ai-guardrail --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area runtime-durability --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area security-evidence --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area trace-interop --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --area workflow-skills --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --priority P0 --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --priority P1 --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --priority P2 --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --priority P3 --capture-card",
    ".codex/hooks/run_with_repo_python.sh scripts/plan_harness_sample_collection.py --include-future --include-accepted --json",
    "python3 tests/test_plan_harness_sample_collection.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area agentic-red-team",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area ai-guardrail",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area runtime-durability",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area security-evidence",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area trace-interop",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --area workflow-skills",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --priority P0",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --priority P1",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --priority P2",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --priority P3",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-approved-remote-interop",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-approved-bounded-incident",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate replace-placeholder-after-real-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-security-workflow-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-bounded-real-incident",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-workflow-task-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-real-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-cross-task-resume",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-distinct-task-class-report",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --capture-gate requires-user-confirmed-high-impact-action",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --ledger-action append-new-pending-slot",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --ledger-action fill-existing-placeholder",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --ledger-action review-upgrade-decision",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --readiness needs-first-real-sample",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --readiness needs-more-real-samples",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --readiness ready-for-upgrade-discussion",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_templates.py --readiness local-sample-only",
    "python3 tests/test_harness_sample_templates.py",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --gap-id GAP-DOES-NOT-EXIST --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area agentic-red-team --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area ai-guardrail --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area runtime-durability --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area security-evidence --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area trace-interop --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --area workflow-skills --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --priority P0 --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --priority P1 --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --priority P2 --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --priority P3 --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-approved-remote-interop --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-approved-bounded-incident --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate replace-placeholder-after-real-event --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-security-workflow-event --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-bounded-real-incident --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-workflow-task-event --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-real-event --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-cross-task-resume --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-distinct-task-class-report --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --capture-gate requires-user-confirmed-high-impact-action --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --readiness needs-first-real-sample --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --readiness needs-more-real-samples --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --readiness ready-for-upgrade-discussion --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --ledger-action append-new-pending-slot --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --ledger-action fill-existing-placeholder --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --ledger-action define-contract-precondition --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --ledger-action review-upgrade-decision --summary",
    ".codex/hooks/run_with_repo_python.sh scripts/build_harness_sample_intake_bundle.py --json",
    "python3 tests/test_harness_sample_intake_bundle.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_placeholder_replacement.py <candidate-jsonl>",
    "python3 tests/test_harness_placeholder_replacement.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_append.py <candidate-jsonl>",
    "python3 tests/test_harness_sample_append.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_outcome.py <candidate-jsonl>",
    "python3 tests/test_harness_sample_outcome.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_future_work_contract_candidate.py <candidate-jsonl>",
    "python3 tests/test_harness_future_work_contract_candidate.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_upgrade_decision_candidate.py <candidate-jsonl>",
    "python3 tests/test_harness_upgrade_decision_candidate.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area agentic-red-team --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area ai-guardrail --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area runtime-durability --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area security-evidence --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area trace-interop --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --area workflow-skills --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --priority P0 --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --priority P1 --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --priority P2 --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --priority P3 --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --gap-id GAP-TRACE-REMOTE-INTEROP --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-approved-remote-interop --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-approved-bounded-incident --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate replace-placeholder-after-real-event --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-security-workflow-event --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-bounded-real-incident --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-workflow-task-event --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-real-event --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-cross-task-resume --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-distinct-task-class-report --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate requires-user-confirmed-high-impact-action --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --capture-gate upgrade-decision-review --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --readiness needs-first-real-sample --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --readiness needs-more-real-samples --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --readiness ready-for-upgrade-discussion --json",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_burn_in_readiness.py --include-future --include-accepted --readiness local-sample-only --json",
    "python3 tests/test_harness_burn_in_readiness.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --gap-id GAP-DOES-NOT-EXIST",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-limit 0",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area agentic-red-team",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area ai-guardrail",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area runtime-durability",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area security-evidence",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area trace-interop",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-area workflow-skills",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-priority P0",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-priority P1",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-priority P2",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-priority P3",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-ledger-action append-new-pending-slot --capture-focus-limit 0",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-ledger-action fill-existing-placeholder",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-ledger-action fill-existing-placeholder --capture-focus-limit 0",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-approved-remote-interop",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-approved-bounded-incident",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate replace-placeholder-after-real-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-security-workflow-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-bounded-real-incident",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-workflow-task-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-real-event",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-cross-task-resume",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-distinct-task-class-report",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-gate requires-user-confirmed-high-impact-action",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-readiness needs-first-real-sample",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --capture-focus --capture-focus-readiness needs-more-real-samples",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --review-state review-ready --review-cards",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_pending_samples.py --include-future --include-accepted --json",
    "python3 tests/test_harness_pending_samples.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_upgrade_decisions.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_future_work_contracts.py",
    "python3 tests/test_harness_future_work_contracts.py",
    ".codex/hooks/run_with_repo_python.sh scripts/check_harness_sample_followup_coverage.py",
    "python3 tests/test_harness_sample_followup_coverage.py",
    "python3 tests/test_governance_workflow_sample_outputs.py",
)
