from __future__ import annotations


Rule = dict[str, object]


def rule(
    name: str,
    level: str,
    ci_coverage: str,
    patterns: tuple[str, ...],
    commands: tuple[str, ...],
    references: tuple[str, ...],
    reason: str,
) -> Rule:
    return {
        "name": name,
        "level": level,
        "ci_coverage": ci_coverage,
        "patterns": patterns,
        "commands": commands,
        "references": references,
        "reason": reason,
    }


RULES: tuple[Rule, ...] = (
    rule(
        "governance-surface",
        "blocking-candidate",
        "covered by governance job; changed-file mapping remains advisory",
        ("AGENTS.md", "docs/ai/**", "docs/requirements/**", ".codex/harness.toml"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_ai_governance.py",),
        (".agents/skills/repo-governed-coding/references/governance-checklist.md",),
        "Shared governance truth changed.",
    ),
    rule(
        "default-context-budget",
        "advisory",
        "manual check only",
        (
            "AGENTS.md",
            "docs/ai/index.md",
            "docs/ai/working-context.md",
            "docs/ai/status/**",
            "docs/ai/adr/**",
            ".agents/skills/**",
            ".codex/skills/**",
            ".codex/skills.catalog.json",
        ),
        (".codex/hooks/run_with_repo_python.sh scripts/check_context_budget.py",),
        (".agents/skills/harness-maintenance/references/verification-commands.md",),
        "Default context or skill surface changed.",
    ),
    rule(
        "repo-local-skills",
        "review-required",
        "manual check unless a project promotes repo skill checks into CI",
        (
            ".agents/skills/**",
            ".codex/skills/**",
            ".codex/skills.catalog.json",
            ".codex/vendor-skills/**",
            ".codex/vendor/**",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_repo_skills.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_skill_catalog.py",
        ),
        ("python3 /Users/coolm/.codex/skills/.system/skill-creator/scripts/quick_validate.py <changed-skill-dir>",),
        "Repo-local skill structure or discoverability may have changed.",
    ),
    rule(
        "requirements-traceability",
        "blocking-candidate",
        "partly covered by governance; shape check remains explicit",
        ("docs/requirements/**",),
        (".codex/hooks/run_with_repo_python.sh scripts/check_requirements_shape.py",),
        (".agents/skills/requirements-traceability-maintenance/",),
        "Requirement, workstream, matrix, or technical-assumption shape may have changed.",
    ),
    rule(
        "standard-agent-eval",
        "advisory",
        "governance job checks dataset shape; skill sample quality remains manual",
        (
            "docs/ai/skill-usage-samples.md",
            "docs/ai/skill-evals/**",
            "docs/ai/evals/**",
            "scripts/check_agent_eval_dataset.py",
            "scripts/run_agent_eval_dataset.py",
            "tests/test_agent_eval_runner.py",
            ".agents/skills/progressive-feature-development/**",
            ".agents/skills/prd-to-project-skills/**",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_skill_usage_samples.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_agent_eval_dataset.py",
            ".codex/hooks/run_with_repo_python.sh scripts/run_agent_eval_dataset.py --dry-run",
            ".codex/hooks/run_with_repo_python.sh scripts/run_agent_eval_dataset.py --id EVAL-005-stop-trace-evidence-contract",
        ),
        ("docs/ai/skill-evals/README.md", "docs/ai/evals/README.md"),
        "Agent eval dataset or skill-eval evidence changed.",
    ),
    rule(
        "agent-trace-standard",
        "blocking-candidate",
        "covered by governance job once standard trace checks are enabled",
        (
            "docs/ai/standards/agent-trace*",
            "scripts/check_agent_trace_schema.py",
            "scripts/export_agent_trace.py",
            "tests/test_agent_trace_schema.py",
            "tests/test_agent_trace_export.py",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_agent_trace_schema.py",
            ".codex/hooks/run_with_repo_python.sh scripts/export_agent_trace.py --input docs/ai/standards/agent-trace-sample.jsonl",
            ".codex/hooks/run_with_repo_python.sh scripts/export_agent_trace.py --input docs/ai/standards/agent-trace-sample.jsonl --format otlp-http-json",
        ),
        ("docs/ai/standards/agent-trace-schema.md",),
        "Standard agent trace schema or validator changed.",
    ),
    rule(
        "tool-contract-registry",
        "blocking-candidate",
        "covered by governance job once tool contract checks are enabled",
        ("docs/ai/tool-contracts/**", "scripts/check_tool_contracts.py", "tests/test_tool_contracts.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_tool_contracts.py",),
        ("docs/ai/tool-contracts/README.md",),
        "Tool contract registry or validator changed.",
    ),
    rule(
        "python-linter",
        "blocking",
        "governance job runs Ruff and git diff whitespace checks",
        (
            "pyproject.toml",
            ".codex/requirements.txt",
            ".github/workflows/governance-and-smoke.yml",
        ),
        (
            ".codex/.venv/bin/python -m ruff check .codex/hooks scripts tests",
            "git diff --check",
        ),
        (
            "pyproject.toml",
            ".agents/skills/harness-maintenance/references/verification-commands.md",
            "docs/ai/check-registry.md",
        ),
        "Python linter configuration, dependencies, or CI entrypoint changed.",
    ),
    rule(
        "github-guardrails",
        "blocking-candidate",
        "local workflow structure is checked; remote enforcement may be UNKNOWN",
        (".github/**", "scripts/check_github_guardrails.py", "scripts/check_pr_touch_conflicts.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py",),
        (".agents/skills/harness-maintenance/references/github-guardrails.md", ".agents/skills/team-pr-conflict-control/"),
        "GitHub workflow, ownership, remote guardrail, or PR overlap surface changed.",
    ),
    rule(
        "supply-chain-evidence",
        "advisory",
        "security evidence workflow produces artifacts but is not a required check",
        (
            ".github/workflows/security-evidence.yml",
            "docs/ai/check-registry.md",
            "docs/ai/security/**",
            ".agents/skills/harness-maintenance/references/supply-chain-security.md",
        ),
        (".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py",),
        (
            ".agents/skills/harness-maintenance/references/supply-chain-security.md",
            "docs/ai/security/supply-chain-provenance-plan.md",
        ),
        "Scorecard, CodeQL, SBOM, or provenance evidence changed.",
    ),
    rule(
        "high-impact-agent-actions",
        "review-required",
        "advisory follow-up only; high-impact actions still require explicit user confirmation",
        (
            "docs/ai/security/agent-action-guardrails.md",
            "docs/ai/security/agent-guardrail-samples.md",
            "--使用细节/真实场景覆盖缺口待确认.md",
            ".github/workflows/**",
            ".github/CODEOWNERS",
            ".github/dependabot.yml",
            "scripts/collect_harness_sample_gaps.py",
            "scripts/check_branch_hygiene.py",
            "scripts/check_github_guardrails.py",
            "scripts/check_pr_touch_conflicts.py",
            "scripts/check_change_triggered_followups.py",
            "scripts/change_triggered_followup_rules.py",
            "tests/test_harness_sample_gaps.py",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_change_triggered_followups.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py",
            ".codex/hooks/run_with_repo_python.sh scripts/collect_harness_sample_gaps.py",
        ),
        ("docs/ai/security/agent-action-guardrails.md", "docs/ai/security/remote-merge-gates.md"),
        "A high-impact agent action surface changed; review confirmation and automation boundaries.",
    ),
    rule(
        "harness-code-shape",
        "blocking-candidate",
        "covered by code shape job for committed code",
        ("scripts/*.py", ".codex/hooks/*.py", ".codex/hooks/**/*.py", "tests/*.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_code_shape.py --staged",),
        (".agents/skills/harness-maintenance/references/code-shape-budget.md",),
        "Harness Python or test code changed.",
    ),
    rule(
        "handoff-compression",
        "advisory",
        "manual compression review only",
        ("docs/ai/handoffs/active/**", "docs/ai/status/**", "docs/ai/working-context.md"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_archive_candidates.py",),
        (".agents/skills/harness-maintenance/references/runtime-governance-compression.md",),
        "Active recovery surface changed; archive candidates may need review.",
    ),
    rule(
        "starter-sync",
        "review-required",
        "validate from starter root before publishing starter changes",
        ("new_pro_standard/**",),
        (
            "cd new_pro_standard && python3 -m unittest discover -s tests",
            "cd new_pro_standard && python3 scripts/check_ai_governance.py",
            "cd new_pro_standard && python3 scripts/check_context_budget.py",
            "cd new_pro_standard && python3 scripts/check_repo_skills.py",
        ),
        ("new_pro_standard/docs/ai/harness-portability-guide.md",),
        "Starter mechanism layer changed; validate the starter from its own root.",
    ),
)
