from __future__ import annotations

from change_triggered_harness_sample_rules import HARNESS_SAMPLE_GAP_COMMANDS, HARNESS_SAMPLE_GAP_PATTERNS
from change_triggered_profile_rules import PROFILE_AND_UPGRADE_RULES
from change_triggered_rule_builder import Rule, WARNING_SAMPLE_CODE_ALIGNMENT_COMMANDS, rule


RULES: tuple[Rule, ...] = (
    rule(
        "governance-surface",
        "blocking-candidate",
        "covered by governance job; changed-file mapping remains advisory",
        ("AGENTS.md", "docs/ai/**", "docs/requirements/**", ".codex/harness.toml"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_ai_governance.py",),
        (".agents/skills/repo-governed-coding/references/governance-checklist.md",),
        "Shared governance truth changed.",
    ),
    rule(
        "default-context-budget",
        "advisory",
        "manual check only",
        (
            "AGENTS.md",
            "docs/ai/index.md",
            "docs/ai/working-context.md",
            "docs/ai/status/**",
            "docs/ai/adr/**",
            ".agents/skills/**",
            ".codex/skills/**",
            ".codex/skills.catalog.json",
        ),
        (".codex/hooks/run_with_repo_python.sh scripts/check_context_budget.py",),
        (".agents/skills/harness-maintenance/references/verification-commands.md",),
        "Default context or skill surface changed.",
    ),
    rule(
        "runtime-token-budget",
        "blocking-candidate",
        "governance job validates no-transcript wiring; real transcript audits remain manual",
        (
            ".codex/harness.toml",
            ".codex/runtime/**",
            ".codex/hooks/stop_runtime_token_pressure.py",
            ".codex/hooks/stop_loop_scope_monitor.py",
            "scripts/check_runtime_token_budget.py",
            "scripts/runtime_token_budget_*.py",
            "scripts/summarize_tool_output.py",
            "tests/test_stop_runtime_token_pressure.py",
            "tests/test_stop_loop_scope_monitor.py",
            "tests/test_runtime_token_budget.py",
            "tests/test_summarize_tool_output.py",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_runtime_token_budget.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_runtime_token_budget.py --transcript <rollout-jsonl>",
            "python3 tests/test_stop_runtime_token_pressure.py",
            "python3 tests/test_stop_loop_scope_monitor.py",
        ),
        (".agents/skills/harness-maintenance/references/runtime-token-budget.md",),
        "Runtime transcript or token-budget policy changed.",
    ),
    rule(
        "stage-checkpoints",
        "advisory",
        "governance job validates checkpoint artifact; real resume samples remain burn-in",
        ("docs/ai/checkpoints/**", ".codex/runtime/execution-snapshots/**", "scripts/check_stage_checkpoints.py", "scripts/check_runtime_execution_snapshots.py", "scripts/evidence_ref_utils.py", "tests/test_stage_checkpoints.py", "tests/test_runtime_execution_snapshots.py", "docs/ai/agentic-harness-gap-roadmap.md"),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_stage_checkpoints.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_runtime_execution_snapshots.py",
            "python3 tests/test_stage_checkpoints.py",
            "python3 tests/test_runtime_execution_snapshots.py",
        ),
        ("docs/ai/checkpoints/README.md",),
        "Stage checkpoint artifact or durable resume checkpoint policy changed.",
    ),
    rule(
        "pre-tool-use-preflight-samples",
        "advisory",
        "governance job validates sample artifact; accepted real preflight warnings remain burn-in",
        (".codex/hooks/pre_tool_use_preflight.py", "docs/ai/standards/pre-tool-use-preflight*", "docs/ai/agentic-harness-gap-roadmap.md", "scripts/check_pre_tool_use_preflight_samples.py", "scripts/evidence_ref_utils.py", "scripts/check_warning_sample_code_alignment.py", "tests/test_pre_tool_use_preflight.py", "tests/test_pre_tool_use_preflight_samples.py", "tests/test_warning_sample_code_alignment.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_pre_tool_use_preflight_samples.py", "python3 tests/test_pre_tool_use_preflight_samples.py", "python3 tests/test_pre_tool_use_preflight.py") + WARNING_SAMPLE_CODE_ALIGNMENT_COMMANDS,
        ("docs/ai/standards/pre-tool-use-preflight.md",),
        "PreToolUse preflight sample policy or burn-in evidence changed.",
    ),
    rule(
        "loop-scope-monitor-samples",
        "advisory",
        "governance job validates sample artifact; accepted real warning samples remain burn-in",
        (".codex/hooks/stop_loop_scope_monitor.py", "docs/ai/standards/loop-scope-monitor*", "docs/ai/agentic-harness-gap-roadmap.md", "scripts/check_loop_scope_monitor_samples.py", "scripts/evidence_ref_utils.py", "scripts/check_warning_sample_code_alignment.py", "tests/test_loop_scope_monitor_samples.py", "tests/test_stop_loop_scope_monitor.py", "tests/test_warning_sample_code_alignment.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_loop_scope_monitor_samples.py", "python3 tests/test_loop_scope_monitor_samples.py", "python3 tests/test_stop_loop_scope_monitor.py") + WARNING_SAMPLE_CODE_ALIGNMENT_COMMANDS,
        ("docs/ai/standards/loop-scope-monitor.md",),
        "Loop/scope monitor sample policy or burn-in evidence changed.",
    ),
    rule(
        "local-trace-summary-samples",
        "advisory",
        "governance job validates sample artifact; additional real local reports remain burn-in",
        ("docs/ai/standards/local-trace-summary*", "docs/ai/agentic-harness-gap-roadmap.md", "scripts/check_local_trace_summary_samples.py", "scripts/evidence_ref_utils.py", "scripts/summarize_runtime_traces.py", "tests/test_local_trace_summary_samples.py", "tests/test_summarize_runtime_traces.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_local_trace_summary_samples.py", "python3 tests/test_local_trace_summary_samples.py", "python3 tests/test_summarize_runtime_traces.py", ".codex/hooks/run_with_repo_python.sh scripts/summarize_runtime_traces.py --runtime-dir .codex/runtime/observations"),
        ("docs/ai/standards/local-trace-summary.md",),
        "Local Trace Summary sample policy or no-network burn-in evidence changed.",
    ),
    rule(
        "harness-sample-gap-evidence",
        "advisory",
        "governance job validates generic gap evidence; real samples remain burn-in",
        HARNESS_SAMPLE_GAP_PATTERNS,
        HARNESS_SAMPLE_GAP_COMMANDS,
        ("docs/ai/standards/harness-sample-gap-evidence.md",),
        "Generic harness gap evidence or local interop burn-in policy changed.",
    ),
    rule(
        "repo-local-skills",
        "review-required",
        "manual check unless a project promotes repo skill checks into CI",
        (
            ".agents/skills/**",
            ".codex/skills/**",
            ".codex/skills.catalog.json",
            ".codex/vendor-skills/**",
            ".codex/vendor/**",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_repo_skills.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_skill_catalog.py",
        ),
        ("python3 /Users/coolm/.codex/skills/.system/skill-creator/scripts/quick_validate.py <changed-skill-dir>",),
        "Repo-local skill structure or discoverability may have changed.",
    ),
    rule(
        "requirements-traceability",
        "blocking-candidate",
        "partly covered by governance; shape check remains explicit",
        ("docs/requirements/**", "scripts/check_requirements_shape.py", "scripts/requirements_source_boundary.py", "scripts/requirements_technical_assumptions.py", "tests/test_requirements_shape.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_requirements_shape.py", ".codex/hooks/run_with_repo_python.sh tests/test_requirements_shape.py"),
        (".agents/skills/requirements-traceability-maintenance/",),
        "Requirement, workstream, matrix, or technical-assumption shape may have changed.",
    ),
    rule(
        "standard-agent-eval",
        "advisory",
        "governance job checks dataset shape; skill sample quality remains manual",
        ("docs/ai/skill-usage-samples.md", "docs/ai/skill-evals/**", "docs/ai/evals/**", "scripts/check_agent_eval_dataset.py", "scripts/run_agent_eval_dataset.py", "scripts/check_task_outcome_eval_dataset.py", "scripts/run_task_outcome_eval_dataset.py", "tests/test_agent_eval_runner.py", "tests/test_task_outcome_eval_dataset.py", ".agents/skills/progressive-feature-development/**", ".agents/skills/prd-to-project-skills/**"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_skill_usage_samples.py", ".codex/hooks/run_with_repo_python.sh scripts/check_agent_eval_dataset.py", ".codex/hooks/run_with_repo_python.sh scripts/run_agent_eval_dataset.py --dry-run", ".codex/hooks/run_with_repo_python.sh scripts/run_agent_eval_dataset.py --id EVAL-005-stop-trace-evidence-contract", ".codex/hooks/run_with_repo_python.sh scripts/check_task_outcome_eval_dataset.py", ".codex/hooks/run_with_repo_python.sh scripts/run_task_outcome_eval_dataset.py --dry-run"),
        ("docs/ai/skill-evals/README.md", "docs/ai/evals/README.md"),
        "Agent eval dataset or skill-eval evidence changed.",
    ),
    rule(
        "agentic-red-team-samples",
        "advisory",
        "governance job validates local replay samples; real incidents remain burn-in",
        ("docs/ai/security/agentic-red-team-samples*", "docs/ai/security/agentic-control-matrix.md", "docs/ai/agentic-harness-gap-roadmap.md", "scripts/check_agentic_red_team_samples.py", "scripts/evidence_ref_utils.py", "tests/test_agentic_red_team_samples.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_agentic_red_team_samples.py", "python3 tests/test_agentic_red_team_samples.py", "python3 tests/test_requirements_shape.py", "python3 tests/test_skill_catalog.py", ".codex/hooks/run_with_repo_python.sh tests/test_workspace_sandbox.py"),
        ("docs/ai/security/agentic-red-team-samples.md", "docs/ai/security/agentic-control-matrix.md"),
        "Agentic red-team replay samples or surface-control burn-in evidence changed.",
    ),
    rule(
        "agent-trace-standard",
        "blocking-candidate",
        "governance job runs trace schema, export, and local summary smoke checks",
        (
            "docs/ai/standards/agent-trace*",
            "docs/ai/standards/trace-remote-interop-report.sample.json",
            "scripts/check_agent_trace_schema.py",
            "scripts/check_remote_trace_interop_report.py",
            "scripts/export_agent_trace.py",
            "scripts/verify_remote_trace_interop.py",
            "scripts/summarize_runtime_traces.py",
            "tests/test_agent_trace_schema.py",
            "tests/test_agent_trace_export.py",
            "tests/test_remote_trace_interop.py",
            "tests/test_summarize_runtime_traces.py",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_agent_trace_schema.py",
            ".codex/hooks/run_with_repo_python.sh scripts/export_agent_trace.py --input docs/ai/standards/agent-trace-sample.jsonl",
            ".codex/hooks/run_with_repo_python.sh scripts/export_agent_trace.py --input docs/ai/standards/agent-trace-sample.jsonl --format otlp-http-json",
            ".codex/hooks/run_with_repo_python.sh scripts/check_remote_trace_interop_report.py",
            "python3 tests/test_summarize_runtime_traces.py",
            "python3 tests/test_remote_trace_interop.py",
            ".codex/hooks/run_with_repo_python.sh scripts/summarize_runtime_traces.py --runtime-dir .codex/runtime/observations",
        ),
        ("docs/ai/standards/agent-trace-schema.md",),
        "Standard agent trace schema or validator changed.",
    ),
    rule("agent-run-provenance", "advisory", "governance job can validate local-first agent-run provenance records", ("docs/ai/standards/agent-run-provenance*", "scripts/check_agent_run_provenance.py", "tests/test_agent_run_provenance.py"), (".codex/hooks/run_with_repo_python.sh scripts/check_agent_run_provenance.py", "python3 tests/test_agent_run_provenance.py"), ("docs/ai/standards/agent-run-provenance.md",), "Agent-run provenance standard, sample records, or validator changed."),
    rule(
        "tool-contract-registry",
        "blocking-candidate",
        "covered by governance job once tool contract checks are enabled",
        ("docs/ai/tool-contracts/**", "scripts/check_tool_contracts.py", "tests/test_tool_contracts.py", "scripts/check_runtime_execution_snapshots.py", "scripts/verify_remote_trace_interop.py", "scripts/check_remote_trace_interop_report.py", "scripts/check_task_outcome_eval_dataset.py", "scripts/run_task_outcome_eval_dataset.py", "scripts/summarize_harness_capabilities.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_tool_contracts.py", "python3 tests/test_tool_contracts.py"),
        ("docs/ai/tool-contracts/README.md",),
        "Tool contract registry or validator changed.",
    ),
    rule(
        "check-burn-in-ledger",
        "advisory",
        "governance job validates ledger coverage",
        (
            "docs/ai/check-registry.md",
            "docs/ai/check-burn-in-ledger.md",
            "scripts/check_burn_in_ledger.py", "scripts/evidence_ref_utils.py",
            "tests/test_check_burn_in_ledger.py",
        ),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_burn_in_ledger.py",
            "python3 tests/test_check_burn_in_ledger.py",
        ),
        ("docs/ai/check-burn-in-ledger.md",),
        "Blocking-candidate burn-in evidence changed.",
    ),
    rule(
        "check-burn-in-upgrade-decisions",
        "advisory",
        "governance job validates check-level upgrade decision coverage",
        ("docs/ai/standards/check-burn-in-upgrade-decisions.jsonl", "scripts/check_burn_in_upgrade_decisions.py", "scripts/evidence_ref_utils.py", "tests/test_burn_in_upgrade_decisions.py"),
        (
            ".codex/hooks/run_with_repo_python.sh scripts/check_burn_in_upgrade_decisions.py",
            ".codex/hooks/run_with_repo_python.sh scripts/check_burn_in_upgrade_decisions.py --json",
            "python3 tests/test_burn_in_upgrade_decisions.py",
        ),
        ("docs/ai/check-burn-in-ledger.md",),
        "Blocking-candidate check-level upgrade decisions changed.",
    ),
    *PROFILE_AND_UPGRADE_RULES,
    rule(
        "python-linter",
        "blocking",
        "governance job runs Ruff and git diff whitespace checks",
        (
            "pyproject.toml",
            ".codex/requirements.txt",
            ".github/workflows/governance-and-smoke.yml",
        ),
        (
            ".codex/.venv/bin/python -m ruff check .codex/hooks scripts tests",
            "git diff --check",
        ),
        (
            "pyproject.toml",
            ".agents/skills/harness-maintenance/references/verification-commands.md",
            "docs/ai/check-registry.md",
        ),
        "Python linter configuration, dependencies, or CI entrypoint changed.",
    ),
    rule(
        "github-guardrails",
        "blocking-candidate",
        "local workflow structure is checked; remote enforcement may be UNKNOWN",
        (".github/**", "scripts/check_github_guardrails.py", "scripts/check_pr_touch_conflicts.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py",),
        (".agents/skills/harness-maintenance/references/github-guardrails.md", ".agents/skills/team-pr-conflict-control/"),
        "GitHub workflow, ownership, remote guardrail, or PR overlap surface changed.",
    ),
    rule(
        "supply-chain-evidence",
        "advisory",
        "security evidence workflow produces artifacts but is not a required check",
        (
            ".github/workflows/security-evidence.yml",
            "docs/ai/check-registry.md",
            "docs/ai/security/**",
            ".agents/skills/harness-maintenance/references/supply-chain-security.md",
        ),
        (".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py",),
        (
            ".agents/skills/harness-maintenance/references/supply-chain-security.md",
            "docs/ai/security/supply-chain-provenance-plan.md",
        ),
        "Scorecard, CodeQL, SBOM, or provenance evidence changed.",
    ),
    rule(
        "high-impact-agent-actions",
        "review-required",
        "advisory follow-up only; high-impact actions still require explicit user confirmation",
        (
            "docs/ai/security/agent-action-guardrails.md",
            "docs/ai/security/agent-guardrail-samples.md",
            "--使用细节/真实场景覆盖缺口待确认.md",
            ".github/workflows/**",
            ".github/CODEOWNERS",
            ".github/dependabot.yml",
            "scripts/collect_harness_sample_gaps.py",
            "scripts/check_branch_hygiene.py",
            "scripts/check_github_guardrails.py",
            "scripts/check_pr_touch_conflicts.py",
            "scripts/check_change_triggered_followups.py",
            "scripts/change_triggered_followup_rules.py",
            "scripts/change_triggered_profile_rules.py",
            ".codex/hooks/pre_tool_use_preflight.py",
            "docs/ai/standards/pre-tool-use-preflight*",
            "tests/test_harness_sample_gaps.py",
            "tests/test_pre_tool_use_preflight.py",
            "tests/test_pre_tool_use_preflight_samples.py",
        ),
        (".codex/hooks/run_with_repo_python.sh scripts/check_change_triggered_followups.py", ".codex/hooks/run_with_repo_python.sh scripts/check_github_guardrails.py", ".codex/hooks/run_with_repo_python.sh scripts/collect_harness_sample_gaps.py", ".codex/hooks/run_with_repo_python.sh scripts/check_pre_tool_use_preflight_samples.py", "python3 tests/test_pre_tool_use_preflight.py"),
        ("docs/ai/security/agent-action-guardrails.md", "docs/ai/security/remote-merge-gates.md"),
        "A high-impact agent action surface changed; review confirmation and automation boundaries.",
    ),
    rule(
        "harness-code-shape",
        "blocking-candidate",
        "covered by code shape job for committed code",
        ("scripts/*.py", ".codex/hooks/*.py", ".codex/hooks/**/*.py", "tests/*.py"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_code_shape.py --staged",),
        (".agents/skills/harness-maintenance/references/code-shape-budget.md",),
        "Harness Python or test code changed.",
    ),
    rule(
        "handoff-compression",
        "advisory",
        "manual compression review only",
        ("docs/ai/handoffs/active/**", "docs/ai/status/**", "docs/ai/working-context.md"),
        (".codex/hooks/run_with_repo_python.sh scripts/check_archive_candidates.py",),
        (".agents/skills/harness-maintenance/references/runtime-governance-compression.md",),
        "Active recovery surface changed; archive candidates may need review.",
    ),
    rule(
        "starter-sync",
        "review-required",
        "validate from starter root before publishing starter changes",
        ("new_pro_standard/**",),
        (
            "cd new_pro_standard && python3 -m unittest discover -s tests",
            "cd new_pro_standard && python3 scripts/check_ai_governance.py",
            "cd new_pro_standard && python3 scripts/check_context_budget.py",
            "cd new_pro_standard && python3 scripts/check_repo_skills.py",
        ),
        ("new_pro_standard/docs/ai/harness-portability-guide.md",),
        "Starter mechanism layer changed; validate the starter from its own root.",
    ),
)
